version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      # Only for local development.
      POSTGRES_DB: fleetdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./ssl:/var/lib/postgresql/certs:ro
    user: postgres
    command: >
      postgres 
      -c ssl=on 
      -c ssl_cert_file=/var/lib/postgresql/certs/server.crt 
      -c ssl_key_file=/var/lib/postgresql/certs/server.key
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fleetdb?sslmode=require
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - ./ssl:/var/lib/postgresql/certs:ro

volumes:
  postgres_data:
